import { AboutPageType } from "@/interfaces/interfaces";
import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import React from "react";

interface Props {
  aboutPageData: AboutPageType;
}

const AboutPage: NextPage<Props> = ({ aboutPageData }) => {
  return (
    <>
      <Head>
        <title>{aboutPageData.title1}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container d-flex justify-content-center align-items-center flex-wrap px-4 my-3">
        <div className="row">
          <div className="col-12 text-center d-flex justify-content-center align-items-center">
            <img src="./sparks.png" alt="" className="sparks" />
            <h4 className="m-0">{aboutPageData.title1}</h4>
          </div>
        </div>
      </div>

      <div className="container d-flex justify-content-center align-items-center flex-wrap px-4">
        <div className="row">
          <div className="col-12 text-center p-0">
            <img src={aboutPageData.about_page_image} alt="" />
          </div>
        </div>
      </div>

      <div className="container d-flex justify-content-start align-items-center flex-wrap pl-4">
        <div className="row">
          <div className="col-12">
            <p style={{ fontSize: "20px" }}>{aboutPageData.title2}</p>
          </div>
        </div>

        <div className="row">
          <div className="col-12">
            <p>{aboutPageData.first_content}</p>
          </div>
        </div>

        <div className="row">
          <div className="col-12">
            <p>{aboutPageData.second_content}</p>
          </div>
        </div>
      </div>
    </>
  );
};

export default AboutPage;

export const getStaticProps: GetStaticProps = async () => {
  const aboutPageRes = await fetch(`http://localhost:5001/about_page`);
  const aboutPageData: AboutPageType = await aboutPageRes.json();
  return {
    props: { aboutPageData },
  };
};
