import { ContactPageType } from "@/interfaces/interfaces";
import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";

interface Props {
  contactPageData: ContactPageType;
}

const ContactPage: NextPage<Props> = ({ contactPageData }) => {
  return (
    <>
      <Head>
        <title>{contactPageData.title1}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container d-flex justify-content-center align-items-center flex-wrap px-4 my-3">
        <div className="row">
          <div className="col-12 text-center d-flex justify-content-center align-items-center">
            <h4>{contactPageData.title1}</h4>
            <img src="./sparks.png" alt="" className="sparks" />
          </div>
        </div>
      </div>

      <div className="container d-flex justify-content-center align-items-center flex-wrap px-4">
        <div className="row">
          <div className="col-12 text-center p-0">
            <img
              src={contactPageData.contact_page_image}
              alt={contactPageData.contact_page_image}
            />
          </div>
        </div>
      </div>

      <div className="container d-flex justify-content-center align-items-center flex-wrap pl-4 mb-5">
        <div className="row">
          <div className="col-12 text-center">
            <h4>{contactPageData.title2}</h4>
            <p>
              <small className="text-muted">{contactPageData.small_text}</small>
            </p>
          </div>

          <div className="col-12 text-center">
            <p>{contactPageData.adress}</p>
          </div>

          <div className="col-12 text-center my-3">
            <h5>{contactPageData.contact}</h5>
            <p>{contactPageData.contact_number}</p>
          </div>

          <div className="col-12 text-center">
            <h5>{contactPageData.work_time}</h5>
            <p className="mb-2">{contactPageData.monday_to_friday}</p>
            <p>{contactPageData.weekend}</p>
          </div>
          <div className="col-12 text-center">
            <Link href={"/"}>
              <button className="w-100 p-2 round footer-button mt-3">
                Кон продавницата
              </button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
};

export default ContactPage;

export const getStaticProps: GetStaticProps = async () => {
  const contactPageRes = await fetch(`http://localhost:5001/contact_page`);
  const contactPageData: ContactPageType = await contactPageRes.json();
  return {
    props: { contactPageData },
  };
};
